name: User Story
description: Create a new user story following Jira-style structure
title: "[STORY] As a <user>, I want <goal> so that <reason>"
labels: ["user-story", "needs-refinement"]
assignees: []
projects: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📋 User Story Definition
        Please complete all sections to ensure the story is ready for refinement and estimation.

  - type: input
    id: story_id
    attributes:
      label: Story ID
      description: Optional tracking ID (e.g., PROJ-123)
      placeholder: "PROJ-XXX"
    validations:
      required: false

  - type: textarea
    id: user_story
    attributes:
      label: User Story Statement
      description: Classic format - Who, What, Why
      placeholder: |
        As a [type of user],
        I want [some goal],
        so that [some reason/benefit].
      value: |
        As a 
        I want 
        so that
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description / Context
      description: Additional context, background, or business justification
      placeholder: Provide any additional details that help understand the "why" behind this story...
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria (Definition of Done)
      description: Specific, testable conditions that must be met. Use Gherkin format (Given/When/Then) if helpful.
      placeholder: |
        - [ ] Criteria 1: Specific measurable outcome
        - [ ] Criteria 2: Another testable condition
        - [ ] Criteria 3: Edge case handling
      value: |
        - [ ] 
        - [ ] 
        - [ ]
    validations:
      required: true

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes / Implementation Details
      description: Architecture considerations, API changes, database impacts, dependencies
      placeholder: |
        - API changes required:
        - Database migrations needed:
        - Dependencies on other stories:
        - Performance considerations:
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Business priority level
      options:
        - Critical (Blocker)
        - High
        - Medium
        - Low
        - Trivial
      default: 2
    validations:
      required: true

  - type: dropdown
    id: story_points
    attributes:
      label: Story Points (Estimation)
      description: Fibonacci scale - leave as "Not Estimated" for refinement session
      options:
        - Not Estimated
        - 1
        - 2
        - 3
        - 5
        - 8
        - 13
        - 21
      default: 0
    validations:
      required: false

  - type: input
    id: sprint
    attributes:
      label: Sprint
      description: Target sprint (if known)
      placeholder: "Sprint 12"
    validations:
      required: false

  - type: textarea
    id: attachments
    attributes:
      label: Attachments / References
      description: Links to designs, documentation, related issues, or external resources
      placeholder: |
        - Design mockups: [Figma link]
        - Related issues: #123, #456
        - Documentation: [Confluence link]
    validations:
      required: false

  - type: checkboxes
    id: definition_of_ready
    attributes:
      label: Definition of Ready Checklist
      description: Ensure this story is ready for development
      options:
        - label: User story format is complete (As a... I want... So that...)
        - label: Acceptance criteria are clear and testable
        - label: Dependencies identified and linked
        - label: Design/mockups attached (if UI related)
        - label: Estimated by the team
        - label: Small enough to complete in one sprint

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes / Discussion
      description: Any other relevant information, open questions, or discussion points
      placeholder: Open questions, assumptions, risks, or notes from refinement sessions...
    validations:
      required: false