package bswe.gamifiedevidencebasednursing.domain.enums;

public enum Mission {
  WOUND_CARE_FOR_PRESSURE_ULCERS,
  FALL_PREVENTION_IN_GERIATRICS,
  PAIN_MANAGEMENT_IN_POSTOPERATIVE_CARE,
  NUTRITIONAL_INTERVENTIONS_FOR_MALNUTRITION,
  PREVENTION_OF_CATHETER_ASSOCIATED_URINARY_TRACT_INFECTIONS

}
